-- MySQL Script generated by MySQL Workbench
-- Tue Dec 12 12:00:35 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DunaMozi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DunaMozi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DunaMozi` DEFAULT CHARACTER SET utf8 COLLATE utf8_hungarian_ci ;
USE `DunaMozi` ;

-- -----------------------------------------------------
-- Table `DunaMozi`.`alkalmazott`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`alkalmazott` (
  `idalkalmazott` INT NOT NULL AUTO_INCREMENT,
  `alkalmazottNev` VARCHAR(200) NULL,
  `jelszo` BLOB(100) NULL,
  `email` VARCHAR(200) NULL,
  `admin` INT NULL,
  `token` TEXT NULL,
  PRIMARY KEY (`idalkalmazott`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DunaMozi`.`kategoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`kategoria` (
  `KategoriaId` INT NOT NULL AUTO_INCREMENT,
  `kategoriNev` VARCHAR(100) NULL,
  PRIMARY KEY (`KategoriaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DunaMozi`.`filmek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`filmek` (
  `idfilmek` INT NOT NULL AUTO_INCREMENT,
  `filmnev` VARCHAR(200) NULL,
  `filmdescription` LONGTEXT NULL,
  `filmhossz` VARCHAR(10) NULL,
  `filmkorhatár` INT NULL,
  `film_KategoriaId` INT NOT NULL,
  PRIMARY KEY (`idfilmek`),
  INDEX `fk_filmek_kategoria1_idx` (`film_KategoriaId` ASC) VISIBLE,
  CONSTRAINT `fk_filmek_kategoria1`
    FOREIGN KEY (`film_KategoriaId`)
    REFERENCES `DunaMozi`.`kategoria` (`KategoriaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DunaMozi`.`VetitoTerem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`VetitoTerem` (
  `idVetitoTerem` INT NOT NULL AUTO_INCREMENT,
  `Terem` VARCHAR(255) NULL,
  PRIMARY KEY (`idVetitoTerem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DunaMozi`.`Vetitesek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`Vetitesek` (
  `idVetitesek` INT NOT NULL AUTO_INCREMENT,
  `vetitesidopont` DATETIME NULL,
  `VetitesHelyID` INT NULL,
  `VetitesFilmID` INT NULL,
  `SzabadJegyek` INT(50) NULL,
  `VetitoTerem_idVetitoTerem` INT NOT NULL,
  `filmek_idfilmek` INT NOT NULL,
  PRIMARY KEY (`idVetitesek`),
  INDEX `fk_Vetitesek_VetitoTerem1_idx` (`VetitoTerem_idVetitoTerem` ASC) VISIBLE,
  INDEX `fk_Vetitesek_filmek1_idx` (`filmek_idfilmek` ASC) VISIBLE,
  CONSTRAINT `fk_Vetitesek_VetitoTerem1`
    FOREIGN KEY (`VetitoTerem_idVetitoTerem`)
    REFERENCES `DunaMozi`.`VetitoTerem` (`idVetitoTerem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vetitesek_filmek1`
    FOREIGN KEY (`filmek_idfilmek`)
    REFERENCES `DunaMozi`.`filmek` (`idfilmek`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DunaMozi`.`ülések`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DunaMozi`.`ülések` (
  `ules_id` INT NOT NULL AUTO_INCREMENT,
  `VetitoTerem_idVetitoTerem` INT NOT NULL,
  `sor` VARCHAR(1) NULL,
  `szekszam` INT NULL,
  `foglalt` TINYINT NULL,
  PRIMARY KEY (`ules_id`),
  INDEX `fk_ülések_VetitoTerem1_idx` (`VetitoTerem_idVetitoTerem` ASC) VISIBLE,
  CONSTRAINT `fk_ülések_VetitoTerem1`
    FOREIGN KEY (`VetitoTerem_idVetitoTerem`)
    REFERENCES `DunaMozi`.`VetitoTerem` (`idVetitoTerem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
