window.onload=function() {document.getElementById("filmek_helye").innerHTML=('<div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_I_The_Motion_Picture.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_II_The_Wrath_of_Khan.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_III_The_Search_For_Spock.jpg" class="img-thumbnail" width="338"height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IV_The_Voyage_Home.jpg" class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_V_The_Final_Frontier.jpg"  class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img  src="IMG/POSTERS/Star_Trek_VI_The_Undiscoverd_Country.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_VII_Generations.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_VIII_First_Contact.jpg" class="img-thumbnail" width="338" height="500" /></div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IX_Insurrection.jpg"    class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_X_Nemesis.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XI_The_Future_Begins.jpg"class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XII_Into_Darkness.jpg"  class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XIII_Beyond.jpg" class="img-thumbnail" width="338" height="500" /> </div>  <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div> <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /> </div></div> ');}
function Katker() {
    var kat = document.getElementById("kat").value;
    if(kat==0){document.getElementById("filmek_helye").innerHTML=('<div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_I_The_Motion_Picture.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_II_The_Wrath_of_Khan.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_III_The_Search_For_Spock.jpg" class="img-thumbnail" width="338"height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IV_The_Voyage_Home.jpg" class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_V_The_Final_Frontier.jpg"  class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img  src="IMG/POSTERS/Star_Trek_VI_The_Undiscoverd_Country.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_VII_Generations.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_VIII_First_Contact.jpg" class="img-thumbnail" width="338" height="500" /></div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IX_Insurrection.jpg"    class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_X_Nemesis.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XI_The_Future_Begins.jpg"class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XII_Into_Darkness.jpg"  class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XIII_Beyond.jpg" class="img-thumbnail" width="338" height="500" /> </div>  <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div> <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /> </div></div> ');}
    if(kat==1){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==2){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==3){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==4){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==5){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==6){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==7){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==8){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==9){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==10){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==11){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==12){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==13){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==14){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==15){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==16){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==17){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==18){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==19){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==20){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==21){document.getElementById("filmek_helye").innerHTML=('<div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_I_The_Motion_Picture.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_II_The_Wrath_of_Khan.jpg"class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_III_The_Search_For_Spock.jpg" class="img-thumbnail" width="338"height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IV_The_Voyage_Home.jpg" class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_V_The_Final_Frontier.jpg"  class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img  src="IMG/POSTERS/Star_Trek_VI_The_Undiscoverd_Country.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_VII_Generations.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_VIII_First_Contact.jpg" class="img-thumbnail" width="338" height="500" /></div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS/Star_Trek_IX_Insurrection.jpg"    class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_X_Nemesis.jpg" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XI_The_Future_Begins.jpg"class="img-thumbnail" width="338" height="500" /> </div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XII_Into_Darkness.jpg"  class="img-thumbnail" width="338" height="500" /> </div></div><div class="row"><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "><img src="IMG/POSTERS/Star_Trek_XIII_Beyond.jpg" class="img-thumbnail" width="338" height="500" /> </div>  <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div> <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /></div><div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 "> <img src="IMG/POSTERS" class="img-thumbnail" width="338" height="500" /> </div></div> ');}
    if(kat==22){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==23){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==24){document.getElementById("filmek_helye").innerHTML=('');}
    if(kat==25){document.getElementById("filmek_helye").innerHTML=('');}
    
    //document.getElementById("demo").innerHTML = ;
    /**<div class="row">
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 ">
                <img src="IMG/POSTERS/" class="img-thumbnail" width="338" height="500" />
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 ">
                <img src="IMG/POSTERS/" class="img-thumbnail" width="338" height="500" />
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 ">
                <img src="IMG/POSTERS/" class="img-thumbnail" width="338" height="500" />
            </div>
            <div class="col-xs-6 col-sm-6 col-md-3 col-lg-3 ">
                <img src="IMG/POSTERS/" class="img-thumbnail" width="338" height="500" />
            </div>
        </div> */
}